controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
auteurs_nouveau:
    path: '/auteurs/nouveau'
    controller: 'App\Controller\AuteurController::nouveau'
    methods: ['GET', 'POST']
register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: ['GET', 'POST']